### ISSUE TITLE
Ability to use more than one USB port/adapter

### ISSUE THREAD

**Issue by sebastianrds** [rkl099/Appinventor-SerialOTG#5]
Hi!

First of all, thanks for your great project!

I want to know if it is possible to add the ability to select more than one USB adapter. I am using a board (an Android TV Box) with 4 USB ports, so I need to comunicate with one serial port (USB adapter 1) a thermal printer, and in another serial port (USB adapter 2) a FT232 board adapter. Can you take in consideration this feature to use more than one serial adapter? I am using Kodular and MIT AppInventor.

Best regards,

Sebastián

**Comment by rkl099** [comment]
Not for the moment. The reason is that this part of the Physicaloid Library (imported from the original) need to be replaced, and I don’t have the time to do it just now. A also need some way to test it. But this feature have been requested by other users, so I add it to my “to do” list.
One question to you, does the extension work without problems with Kodular?
